apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb 
  namespace: argo-cd
  finalizers:
    # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: influxdb
    targetRevision: 6.3.13
    helm:
      values: |
        clusterDomain: localdev.me
        auth:
          ## @param auth.enabled Enable/disable authentication (Variable to keep compatibility with InfluxDB&trade; v1, in v2 it will be ignored)
          enabled: true
          ## @param auth.usePasswordFiles Whether to use files to provide secrets instead of env vars.
          usePasswordFiles: false
          ## InfluxDB&trade; admin credentials
          admin:
            ## @param auth.admin.username InfluxDB&trade; admin user name
            username: admin
            ## @param auth.admin.password InfluxDB&trade; admin user's password
            password: "RssNj2CQ"
            ## @param auth.admin.token InfluxDB&trade; admin user's token. Only valid with InfluxDB&trade; v2
            token: "RssNj2CQeUwIRfYDFCMb"
            ## @param auth.admin.org InfluxDB&trade; admin user's org. Only valid with InfluxDB&trade; v2
            ##
            org: primary
            ## @param auth.admin.bucket InfluxDB&trade; admin user's bucket. Only valid with InfluxDB&trade; v2
            ##
            bucket: primary
            ## @param auth.admin.retention InfluxDB&trade; admin user's bucket retention. Only valid with InfluxDB&trade; v2
            ##
            #retention: ""
        ingress:
          enabled: true
          ingressClassName: "system-ingress"
          hostname: influxdb.localdev.me
          annotations:
            ingress.kubernetes.io/ssl-redirect: "true"
            ingress.kubernetes.io/proxy-body-size: "0"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            cert-manager.io/cluster-issuer: dev-ca-issuer
            cert-manager.io/common-name: influxdb.localdev.me
            cert-manager.io/subject-organizations: "home dev lab"
            cert-manager.io/subject-countries: "RU"
            cert-manager.io/subject-localities: "Moscow"
            cert-manager.io/duration: "9125h"
            cert-manager.io/renew-before: "360h"
            cert-manager.io/usages: "server auth"
            cert-manager.io/private-key-algorithm: RSA
            cert-manager.io/private-key-encoding: "PKCS8"
            cert-manager.io/private-key-size: "4096"
            cert-manager.io/private-key-rotation-policy: Always
          tls: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: influxdb 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true