apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafdrop
  namespace: argo-cd
  finalizers:
    # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/obsidiandynamics/kafdrop'
    chart: chart
    helm:
      values: |  
        kafdrop:
          enabled: true
          replicaCount: 1
          kafka:
            brokerConnect: kafka-dev-broker-0.kafka-dev-broker-headless.kafka.svc.cluster.local:9092, kafka-dev-broker-1.kafka-dev-broker-headless.kafka.svc.cluster.local:9092
          service:
            type: ClusterIP
            targetPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 400Mi
          ingress:
            enabled: true
            ingressClassName: "system-ingress"
            hostname: kafka.localdev.me
            annotations:
              ingress.kubernetes.io/ssl-redirect: "true"
              ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              cert-manager.io/cluster-issuer: dev-ca-issuer
              cert-manager.io/common-name: kafka.localdev.me
              cert-manager.io/subject-organizations: "home dev lab"
              cert-manager.io/subject-countries: "RU"
              cert-manager.io/subject-localities: "Moscow"
              cert-manager.io/duration: "9125h"
              cert-manager.io/renew-before: "360h"
              cert-manager.io/usages: "server auth"
              cert-manager.io/private-key-algorithm: RSA
              cert-manager.io/private-key-encoding: "PKCS8"
              cert-manager.io/private-key-size: "4096"
              cert-manager.io/private-key-rotation-policy: Always
            tls: true
          resources:
            requests:
              cpu: 1
              memory: 512Mi
            limits:
              cpu: 2
              memory: 1024Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true