apiVersion: v1
kind: Secret
metadata:
  name: kafka-helm-repo
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://helm-charts.itboon.top/kafka
  name: kafka-repo
  type: helm