apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argo-cd
  finalizers:
    # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: kafka
    targetRevision: 29.3.13
    helm:
      values: |  
        kafka:
          enabled: true
          controller:
            replicaCount: 0
            automountServiceAccountToken: true
          broker:
            replicaCount: 2
            persistence:
              size: 1Gi
            automountServiceAccountToken: true
          kraft:
            enabled: false
          zookeeper:
            enabled: true
            persistence:
              size: 1Gi
          listeners:
            client:
              protocol: PLAINTEXT
            controller:
              protocol: PLAINTEXT
            interbroker:
              protocol: PLAINTEXT
            external:
              protocol: PLAINTEXT
          externalAccess:
            enabled: true
            broker:
              service:
                type: ClusterIP
                domain: 192.168.243.6
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true