apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mail-relay
  namespace: argo-cd
  finalizers:
    # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/kponevaphone/infra'
    path: Utils/k3s-dev/manifests/mail-relay/
    targetRevision: main 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mail-relay
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true