---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: grafana
  namespace: grafana
spec:
  repo: 'https://charts.bitnami.com/bitnami'
  chart: grafana
  version: 11.3.10
  targetNamespace: grafana
  valuesContent: |-
    clusterDomain: localdev.me
    admin:
      user: "admin"
      existingSecretPasswordKey: password
    ingress:
      enabled: true
      ingressClassName: "system-ingress"
      hostname: grafana.localdev.me
      annotations:
        ingress.kubernetes.io/ssl-redirect: "true"
        ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        cert-manager.io/cluster-issuer: dev-ca-issuer
        cert-manager.io/common-name: grafana.localdev.me
        cert-manager.io/subject-organizations: "home dev lab"
        cert-manager.io/subject-countries: "RU"
        cert-manager.io/subject-localities: "Moscow"
        cert-manager.io/duration: "9125h"
        cert-manager.io/renew-before: "360h"
        cert-manager.io/usages: "server auth"
        cert-manager.io/private-key-algorithm: RSA
        cert-manager.io/private-key-encoding: "PKCS8"
        cert-manager.io/private-key-size: "4096"
        cert-manager.io/private-key-rotation-policy: Always
      tls: true